version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
